name: Run

on:
  schedule:
    - cron: "0 0 * * 1" # weekly (Monday)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Download data
        run: make data

      - name: Build index.html
        run: make index

      - name: Upload dataset
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: make upload

      - name: Commit index.html updates
        run: |
          if git diff --quiet -- index.html; then
            echo "No index.html changes"
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "ðŸ¤– Update index.html"
          git push
